### ISSUE TITLE
Add type badges for options

### ISSUE THREAD

**Issue by drydenwilliams** [thegreenwebfoundation/developer-docs#27]
**Is your feature request related to a problem? Please describe.**
Yep, it's tricky to know what is optional or not within the `options` object. 

**Describe the solution you'd like**
Would like to extend the [changing-variables](https://developers.thegreenwebfoundation.org/co2js/tutorials/customise-website-carbon-calculations/#changing-variables)

**Describe alternatives you've considered**
Could have the `Optional` badge like in other params

<img width="276" alt="Screenshot 2023-08-03 at 18 45 41" src="https://github.com/thegreenwebfoundation/co2.js/assets/4403089/99493834-8547-47af-bfab-c4818d3febdc">

**Comment by fershad** [comment]
Since this issue is related to the docs website, I've moved it into that repo (out of the CO2.js repo)
