### ISSUE TITLE
Revisit multicheck API repsonse info

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/developer-docs#34]
If looks like our co2.js hosting check methods may return richer information soon.

See the issue linked below for more - **Return verbose response for green hosting checks**:

https://github.com/thegreenwebfoundation/co2.js/issues/189

**Comment by fershad** [comment]
Hi @Ayush9026 thanks for the enthusiasm. We have yet to pencil this update into our internal roadmap for CO2.js. Once we've done that we'll update here.

**Comment by fershad** [comment]
This was updated in #48
