### ISSUE TITLE
Update README with Community and Contributing Information

### ISSUE THREAD

**Issue by Ayush9026** [thegreenwebfoundation/developer-docs#46]
**Is your feature request related to a problem? Please describe.**

The current documentation for contributors lacks clarity and detail, making it challenging for new contributors to understand how to get started with the project effectively. This can lead to confusion and delays in onboarding new contributors.

**Describe the solution you'd like**

I would like to improve the documentation for contributors by Updating a contributing.md file to the repository. This file will include detailed instructions on how to contribute to the project, such as setting up the development environment, creating pull requests, and following the project's coding standards and best practices.

**Describe alternatives you've considered**

An alternative solution would be to update the existing README.md file with the contribution guidelines. However, updating contributing.md file allows for better organization and clarity, making it easier for contributors to find the information they need.

**Additional context**

Having a contributing.md file is essential for welcoming new contributors and streamlining the contribution process. It ensures that all contributors have access to clear and comprehensive guidelines, leading to a more collaborative and productive development environment.

**Comment by fershad** [comment]
Hi @Ayush9026.
We currently have a [CONTRIBUTING.md](https://github.com/thegreenwebfoundation/developer-docs/blob/main/CONTRIBUTING.md) file in this repo, which links back to our organisation's contributing guidelines. 

As the stewards of this project, and owners of the website it is attached to, we will take responsibility to update the contributing policy.

Updating this guidance is something we've talked about internally, and do plan to get around to as part of the Google Season of Docs. Please see the FAQ title "Where can I find out how I can contribute to this project?" in [our blog post](https://www.thegreenwebfoundation.org/news/google-season-of-docs-co2-js-contributor-pathways/) for information about how those interested in contributing can know which issues are open as part of that project. At the moment, we have not created any issues specific to work for that project as we are still planning the work required internally.
