### ISSUE TITLE
Typos in contributor.md file

### ISSUE THREAD

**Issue by hanopcan** [thegreenwebfoundation/developer-docs#56]
**Describe the bug**
There are a few small typos in the contributor.md file.

**To Reproduce**
1. Go to [CONTRIBUTING.MD file](https://github.com/thegreenwebfoundation/developer-docs/blob/main/CONTRIBUTING.md)
2. Have a read, you'll spot a few typos

**Expected behavior**
Ideally no typos!

**Screenshots**
n/a

**Additional context**

**Comment by fershad** [comment]
Thank you for the PR @hanopcan
