### ISSUE TITLE
Create documentation for switching models in CO2.js

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/developer-docs#9]
Once https://github.com/thegreenwebfoundation/co2.js/pull/96 gets merged, users will have an easier way to change to using the Sustainable Web Design model in CO2.js

```js
import CO2 from "./co2.js";
co2 = new CO2({ model: 'swd' });
```

This needs to be documented, as there is currently no material in the CO2.js docs on how to change models.

**Comment by mrchrisadams** [comment]
I've merged this change in now.

I'll make a new npm release this morning to demonstrate the different methods in an observable notebook.

This might be useful to refer to in the docs, it it's also something that I think can be done independently of this issue here.

**Comment by fershad** [comment]
This has been added in #10
